In [12]:
print("Hello, Machine Learning Internship!")

Hello, Machine Learning Internship!

In [13]:
python -m pip install pandas numpy scikit-learn matplotlib seaborn

SyntaxError: invalid syntax (1444693492.py, line 1)

In [14]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries are ready!")

All libraries are ready!

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries imported successfully!")

Libraries imported successfully!

In [16]:
from google.colab import files

uploaded = files.upload()

KeyboardInterrupt:

In [ ]:
  df = pd.read_csv("netflix_titles.csv")

print("Dataset loaded successfully!")
print(df.head())

In [ ]:
from google.colab import files

uploaded = files.upload()

In [ ]:
import os

print(os.listdir())

In [ ]:
import pandas as pd

df = pd.read_csv("netflix_titles.csv")

print("Dataset loaded successfully!")
print(df.head())

In [ ]:
import pandas as pd

df = pd.read_csv("netflix_titles.csv")

print("Dataset loaded successfully!")
print(df.head())

In [ ]:
import pandas as pd

df = pd.read_csv("netflix_titles.csv")

print("Dataset loaded successfully!")
print(df.head())

In [ ]:
import pandas as pd

df = pd.read_csv("netflix_titles.csv")

print("Dataset loaded successfully!")
print(df.head())

In [ ]:
# @title AI prompt cell

import ipywidgets as widgets
from IPython.display import display, HTML, Markdown,clear_output
from google.colab import ai

dropdown = widgets.Dropdown(
    options=[],
    layout={'width': 'auto'}
)

def update_model_list(new_options):
    dropdown.options = new_options
update_model_list(ai.list_models())

text_input = widgets.Textarea(
    placeholder='Ask me anything....',
    layout={'width': 'auto', 'height': '100px'},
)

button = widgets.Button(
    description='Submit Text',
    disabled=False,
    tooltip='Click to submit the text',
    icon='check'
)

output_area = widgets.Output(
     layout={'width': 'auto', 'max_height': '300px','overflow_y': 'scroll'}
)

def on_button_clicked(b):
    with output_area:
        output_area.clear_output(wait=False)
        accumulated_content = ""
        for new_chunk in ai.generate_text(prompt=text_input.value, model_name=dropdown.value, stream=True):
            if new_chunk is None:
                continue
            accumulated_content += new_chunk
            clear_output(wait=True)
            display(Markdown(accumulated_content))

button.on_click(on_button_clicked)
vbox = widgets.GridBox([dropdown, text_input, button, output_area])

display(HTML("""
<style>
.widget-dropdown select {
    font-size: 18px;
    font-family: "Arial", sans-serif;
}
.widget-textarea textarea {
    font-size: 18px;
    font-family: "Arial", sans-serif;
}
</style>
"""))
display(vbox)

In [ ]:
from google.colab import files

uploaded = files.upload()

print("Uploaded files:", list(uploaded.keys()))

In [ ]:
import pandas as pd

csv_files = [name for name in uploaded.keys()
             if name.lower().endswith(".csv")]

if csv_files:
    filename = csv_files[0]
    df = pd.read_csv(filename)

    print("Dataset loaded successfully!")
    print("Dataset shape:", df.shape)
    display(df.head())
else:
    print("No CSV file was uploaded. Please upload the extracted CSV file.")

In [3]:
from google.colab import files

uploaded = files.upload()

print("Uploaded files:", list(uploaded.keys()))

Saving netflix_titles.csv to netflix_titles (1).csv
Uploaded files: ['netflix_titles (1).csv']

In [4]:
import pandas as pd

csv_files = [name for name in uploaded.keys()
             if name.lower().endswith(".csv")]

if csv_files:
    filename = csv_files[0]
    df = pd.read_csv(filename)

    print("Dataset loaded successfully!")
    print("Dataset shape:", df.shape)
    display(df.head())
else:
    print("No CSV file was uploaded. Please upload the extracted CSV file.")

Dataset loaded successfully!
Dataset shape: (8807, 12)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
print("Number of rows and columns:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Number of rows and columns: (8807, 12)

Column names:
['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

First 5 rows:

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [6]:
print(df.isnull().sum())

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [7]:
df["listed_in"] = df["listed_in"].fillna("")
df["description"] = df["description"].fillna("")

df["combined_features"] = (
    df["listed_in"] + " " + df["description"]
)

display(df[["title", "combined_features"]].head())

                   title                                  combined_features
0   Dick Johnson Is Dead  Documentaries As her father nears the end of h...
1          Blood & Water  International TV Shows, TV Dramas, TV Mysterie...
2              Ganglands  Crime TV Shows, International TV Shows, TV Act...
3  Jailbirds New Orleans  Docuseries, Reality TV Feuds, flirtations and ...
4           Kota Factory  International TV Shows, Romantic TV Shows, TV ...

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf.fit_transform(
    df["combined_features"]
)

print("TF-IDF matrix shape:", tfidf_matrix.shape)

TF-IDF matrix shape: (8807, 18895)

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf.fit_transform(
    df["combined_features"]
)

print("TF-IDF matrix shape:", tfidf_matrix.shape)

TF-IDF matrix shape: (8807, 18895)

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries imported successfully!")

Libraries imported successfully!

In [11]:
print("Dataset shape:", df.shape)
print(df.columns.tolist())
print(df.isnull().sum())

Dataset shape: (8807, 13)
['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description', 'combined_features']
show_id                 0
type                    0
title                   0
director             2634
cast                  825
country               831
date_added             10
release_year            0
rating                  4
duration                3
listed_in               0
description             0
combined_features       0
dtype: int64

In [12]:
df["listed_in"] = df["listed_in"].fillna("")
df["description"] = df["description"].fillna("")

df["combined_features"] = (
    df["listed_in"] + " " + df["description"]
)

print(df[["title", "combined_features"]].head())

                   title                                  combined_features
0   Dick Johnson Is Dead  Documentaries As her father nears the end of h...
1          Blood & Water  International TV Shows, TV Dramas, TV Mysterie...
2              Ganglands  Crime TV Shows, International TV Shows, TV Act...
3  Jailbirds New Orleans  Docuseries, Reality TV Feuds, flirtations and ...
4           Kota Factory  International TV Shows, Romantic TV Shows, TV ...

In [13]:
tfidf = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf.fit_transform(
    df["combined_features"]
)

print(tfidf_matrix.shape)

(8807, 18895)

In [14]:
similarity_matrix = cosine_similarity(tfidf_matrix)

print("Similarity calculated successfully!")

Similarity calculated successfully!

In [16]:
indices = pd.Series(
    df.index,
    index=df["title"].str.lower()
).drop_duplicates()


def recommend_titles(title, number=5):
    title = title.strip().lower()

    if title not in indices:
        print("Title not found in the dataset.")
        return

    idx = indices[title]

    scores = list(enumerate(similarity_matrix[idx]))

    scores = sorted(
        scores,
        key=lambda item: item[1],
        reverse=True
    )

    scores = [
        item for item in scores
        if item[0] != idx
    ]

    recommended_indices = [
        item[0] for item in scores[:number]
    ]

    return df.iloc[recommended_indices][
        ["title", "type", "listed_in", "release_year"]
    ]

In [17]:
recommend_titles("Stranger Things")

,title,type,listed_in,release_year
4733,Rowdy Rathore,Movie,"Action & Adventure, Comedies, International Mo...",2012
3986,The OA,TV Show,"TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy",2019
1487,Sakho & Mangane,TV Show,"Crime TV Shows, International TV Shows, TV Dramas",2019
8083,Star-Crossed,TV Show,"Romantic TV Shows, TV Dramas, TV Sci-Fi & Fantasy",2014
241,Manifest,TV Show,"TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy",2021

In [18]:
recommend_titles("The Adam Project")

Title not found in the dataset.

In [19]:
df[df["title"].str.contains(
    "Stranger Things",
    case=False,
    na=False
)][["title", "type"]]

                       title     type
3685         Stranger Things  TV Show
5200  Beyond Stranger Things  TV Show

In [20]:
recommend_titles("The Adam Project")

Title not found in the dataset.

In [21]:
recommend_titles("Stranger Things")

,title,type,listed_in,release_year
4733,Rowdy Rathore,Movie,"Action & Adventure, Comedies, International Mo...",2012
3986,The OA,TV Show,"TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy",2019
1487,Sakho & Mangane,TV Show,"Crime TV Shows, International TV Shows, TV Dramas",2019
8083,Star-Crossed,TV Show,"Romantic TV Shows, TV Dramas, TV Sci-Fi & Fantasy",2014
241,Manifest,TV Show,"TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy",2021

In [22]:
```python
def recommend_titles(title, number=5):
    title = title.strip().lower()

    if title not in indices:
        print("Title not found in the dataset.")
        return

    idx = indices[title]

    scores = list(enumerate(similarity_matrix[idx]))
    scores = sorted(scores, key=lambda item: item[1], reverse=True)

    # Remove the original title from the recommendations
    scores = [item for item in scores if item[0] != idx]

    # Select the top recommendations
    top_scores = scores[:number]

    recommended_indices = [item[0] for item in top_scores]
    similarity_scores = [item[1] for item in top_scores]

    # Create the output table
    results = df.iloc[recommended_indices][
        ["title", "type", "listed_in", "release_year"]
    ].copy()

    results["similarity_score"] = [
        round(score, 3) for score in similarity_scores
    ]

    return results
```

SyntaxError: invalid syntax (3015014573.py, line 1)

In [23]:
def recommend_titles(title, number=5):
    title = title.strip().lower()

    if title not in indices:
        print("Title not found in the dataset.")
        return

    idx = indices[title]

    scores = list(enumerate(similarity_matrix[idx]))
    scores = sorted(scores, key=lambda item: item[1], reverse=True)
    scores = [item for item in scores if item[0] != idx]

    top_scores = scores[:number]

    recommended_indices = [item[0] for item in top_scores]
    similarity_scores = [item[1] for item in top_scores]

    results = df.iloc[recommended_indices][
        ["title", "type", "listed_in", "release_year"]
    ].copy()

    results["similarity_score"] = [
        round(score, 3) for score in similarity_scores
    ]

    return results

In [24]:
recommend_titles("Stranger Things")

,title,type,listed_in,release_year,similarity_score
4733,Rowdy Rathore,Movie,"Action & Adventure, Comedies, International Mo...",2012,0.275
3986,The OA,TV Show,"TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy",2019,0.260
1487,Sakho & Mangane,TV Show,"Crime TV Shows, International TV Shows, TV Dramas",2019,0.232
8083,Star-Crossed,TV Show,"Romantic TV Shows, TV Dramas, TV Sci-Fi & Fantasy",2014,0.231
241,Manifest,TV Show,"TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy",2021,0.229

In [25]:
recommend_titles("The Adam Project")

Title not found in the dataset.

In [26]:
recommend_titles("This Title Does Not Exist")

Title not found in the dataset.

In [27]:
df[df["title"].str.contains("Adam Project", case=False, na=False)][
    ["title", "type", "release_year"]
]

Empty DataFrame
Columns: [title, type, release_year]
Index: []

In [28]:
recommend_titles("The OA")

,title,type,listed_in,release_year,similarity_score
8421,The Messengers,TV Show,"TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy",2015,0.335
3685,Stranger Things,TV Show,"TV Horror, TV Mysteries, TV Sci-Fi & Fantasy",2019,0.260
7381,Maharakshak Devi,TV Show,"International TV Shows, TV Action & Adventure,...",2015,0.255
2346,"Roswell, New Mexico",TV Show,"Classic & Cult TV, TV Dramas, TV Sci-Fi & Fantasy",2020,0.252
241,Manifest,TV Show,"TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy",2021,0.252

In [29]:
indices = pd.Series(
    df.index,
    index=df["title"].str.strip().str.lower()
).drop_duplicates()

In [30]:
recommend_titles("The Adam Project")

Title not found in the dataset.

In [31]:
indices = pd.Series(
    df.index,
    index=df["title"].str.strip().str.lower()
).drop_duplicates()

In [32]:
recommend_titles("The Adam Project")

Title not found in the dataset.

In [33]:
df[["title", "type"]].sample(10, random_state=42)

                                 title     type
4970                   Game Over, Man!    Movie
3362      Arsenio Hall: Smart & Classy    Movie
5494                          Kazoops!  TV Show
1688              We Are the Champions  TV Show
1349  Pablo Escobar, el patrón del mal  TV Show
4862      Saint Seiya: The Lost Canvas  TV Show
2676                             Fauda  TV Show
487               The Cook of Castamar  TV Show
1671      The App That Stole Christmas    Movie
5028                              Mute    Movie

In [34]:
recommend_titles("Manifest")

,title,type,listed_in,release_year,similarity_score
3986,The OA,TV Show,"TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy",2019,0.252
4588,My Friend Pinto,Movie,"Comedies, International Movies, Sci-Fi & Fantasy",2011,0.236
3685,Stranger Things,TV Show,"TV Horror, TV Mysteries, TV Sci-Fi & Fantasy",2019,0.229
3526,The I-Land,TV Show,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",2019,0.221
5939,The 4400,TV Show,"TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy",2007,0.212